---
id: 884e0758-ebf4-4509-8e6d-887053be3869
---
usecase-beta
direction LR
actor Admin("Admin")
actor Auteur("Auteur")
actor visiteur("visiteur")

system [ "blog"]



Admin -- Gère le contenu -- system
Auteur --Rédige et gère ses articles -- system
visiteur -- Consulte les articles publiés -- system