flowchart LR

    CLIENT["CLIENT
    ─────────────
    id_client
    nom_client
    email_client"]

    COMMANDE["COMMANDE
    ─────────────
    numero_commande
    date_commande"]

    PRODUIT["PRODUIT
    ─────────────
    id_produit
    nom_produit
    prix_produit"]

    R1{"PASSE"}

    R2{"CONTIENT
    ─────────
    quantite_commande"}

    CLIENT ---|"1,N"| R1
    R1 ---|"1,1"| COMMANDE

    COMMANDE ---|"0,N"| R2
    R2 ---|"0,N"| PRODUIT